### PR TITLE
Table created for animals

### PR DESCRIPTION
**Pull request by Abdulwhbhussain**
Project requirements
Use [this template](https://github.com/microverseinc/curriculum-template-databases) to generate your repo.
Create a database named vet_clinic.
Create a table named animals with the following columns:
id: integer
name: string
date_of_birth: date
escape_attempts: integer
neutered: boolean
weight_kg: decimal
Copy the SQL you used in the previous point into the schema.sql file in the generated repository.
Insert the following data:
Animal: His name is Agumon. He was born on Feb 3rd, 2020, and currently weighs 10.23kg. He was neutered and he has never tried to escape.
Animal: Her name is Gabumon. She was born on Nov 15th, 2018, and currently weighs 8kg. She is neutered and she has tried to escape 2 times.
Animal: His name is Pikachu. He was born on Jan 7th, 2021, and currently weighs 15.04kg. He was not neutered and he has tried to escape once.
Animal: Her name is Devimon. She was born on May 12th, 2017, and currently weighs 11kg. She is neutered and she has tried to escape 5 times.
Copy the SQL you used in the previous point into the data.sql file in the generated repository.
Write queries for the following quests:
Find all animals whose name ends in "mon".
List the name of all animals born between 2016 and 2019.
List the name of all animals that are neutered and have less than 3 escape attempts.
List the date of birth of all animals named either "Agumon" or "Pikachu".
List name and escape attempts of animals that weigh more than 10.5kg
Find all animals that are neutered.
Find all animals not named Gabumon.
Find all animals with a weight between 10.4kg and 17.3kg (including the animals with the weights that equals precisely 10.4kg or 17.3kg)
Take a screenshot of the results of your queries.
Copy the SQL you used in the previous point into the queries.sql file in the generated repository.
Remember to add the screenshot with the results of your queries to your Pull Request description.
 **I don't know how to get the result of first query.**
query-result1
query-result3
query-result2
query-result5
query-result6
query-result7
query-result4

### CODE REVIEW

**Review by mukhammadrizooff — APPROVED** [review]
Hi @Abdulwhbhussain, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

 

## Highlights
- Correct GitFlow ✔️ 
- Good implementations ✔️
- Descriptive `README` file ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by mikethreels — COMMENTED** [review]
Hi Wahab, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- good job creating the table and adding the values

## Required Changes ♻️
- [ ] According to the requirements you should have included the below queries:
   - Find all animals whose name ends in "mon".
   - List the name of all animals born between 2016 and 2019.
   - List the name of all animals that are neutered and have less than 3 escape attempts.
   - List the date of birth of all animals named either "Agumon" or "Pikachu".
   - List name and escape attempts of animals that weigh more than 10.5kg
   - Find all animals that are neutered.
   - Find all animals not named Gabumon.
   - Find all animals with a weight between 10.4kg and 17.3kg (including the animals with weights that equal precisely 10.4kg or 17.3kg)

right now, in the branch you submitted for review, there is only one query which was not part of the requirements:
https://github.com/Abdulwhbhussain/Vet-Clinic-Database/blob/8ea2af50abd8cbe1c96687f3ab818e57fa621aad/queries.sql#L3
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Abdulwhbhussain** [comment]
I Updated the Branch with the required Queries But I can't create new Pull Request!

**Review by omar-muhamad — COMMENTED** [review]
# Invalid ❌

Hi @Abdulwhbhussain,

#### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

#### Your Code Review Request is marked as invalid for this reason:

- [ ] It seems that you are repeating the module, Please create a new repo for each project with PRs that have all changes and have not been approved or merged before.

- [ ] You didn't document your work professionally:
   -  You used the [Microverse README template](https://github.com/microverseinc/readme-template) but you forgot to edit it with your personal and project data.


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Review by omar-muhamad — COMMENTED** [review]
# Invalid ❌

Hi @Abdulwhbhussain,

#### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

#### Your Code Review Request is marked as invalid for this reason:

- [ ] It seems that you are repeating the module, Please create a new repo for each project with PRs that have all changes and have not been approved or merged before.

- [ ] You didn't document your work professionally:
   -  You used the [Microverse README template](https://github.com/microverseinc/readme-template) but you forgot to edit it with your personal and project data.


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Pull request merged**
